### ISSUE TITLE
Intel XDK

### ISSUE THREAD

**Issue by cruztaceo** [cranberrygame/com.cranberrygame.cordova.plugin.facebook#1]
I created my game using C2 and used the plugin in my project.

When I want to compile the game using Intel XDK 3491 is throwing this exception:

`com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)`

**Comment by arijan108** [comment]
Hey man, got the same problem, tried using Intel XDK 3400 and the 3491 version. Did you maybe find the solution?

**Comment by cruztaceo** [comment]
@arijan108 not yet... I know that there are other plugins from @cranberrygame that works with this XDK version, but seems that this plugin is not updated.

**Comment by arijan108** [comment]
Just now I was able to "solve" that -AccessibilityServiceInfoCompatIcs- part, since I am getting a new error now. I am dealing with " Landroid/support/annotation/AnimRes ". I am trying to use the Revmob and/or Vungle plug-in, both are having a problem with the Facebook plugin.

**Comment by blackheart99999** [comment]
'Im getting te build Error in XDK, not using any other plugin, just the test file from construct 2 with cranberry favebook plugin.
Has anybody solved the issue, I really need the facebook plugin into my app, Im stuck because of this.

**Comment by arijan108** [comment]
@blackheart99999 when building the app, 2 important things to consider is to use Phonegap Facebook plugin in Construct2 and when adding the plugin in XDK, add the Facebook Plugin that is featured a.k.a Facebook4 / Facebook Connect ( by jeduan):

https://github.com/jeduan/cordova-plugin-facebook4

**Comment by blackheart99999** [comment]
@arijan108 Phonegap Facebook is cranberry's depreciated plugin for C2, I tried it, but XDK keep loading the cranberry facebook plugin from git, and throws error that plugin not found, even after clicking Remove, it again tries to download it and goes into error loop. I tried removing it from config.xml, but it didnt work, can't open project in XDK ?

**Comment by blackheart99999** [comment]
While using the depreciated phonegap facebook C2 plugin, XDK got stuck finding the old plugin from git, Then I tried with cranberry cordova facebook, and Jeduan's XDK facebook... It worked and app compiled.
But Now I'm able to only trigger login which brings up the app page for permissions, but share prompt does nothing ?

**Comment by arijan108** [comment]
I am using Cranberry Phonegap Facebook plugin and on XDK the jeduan Facebook4 to compile the app. However, I am not certain of the share options as I didn't need those. I only needed the users ID and Name, which was enough for me to consider it "working".

Cranberries Facebook share plugin has problems with multiple dex files using the plugin in XDK. I didn't ever test the share prompt, so I am not certain what might be the problem.
